version: '3'

services:
  app:
    build: .
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - '.:/app'
    ports:
      - "5000:5000"
    networks:
      default:
        aliases:
        - botservice.hypechat

networks:
  default:
    external:
      name: hypechat_default